### ISSUE TITLE
'r2' writes tab as spaces

### ISSUE THREAD

**Issue by Zepeng-Mu** [chrchang/plink-ng#103]
I am using the `--r2 gz` command. The output file should be tab-delimited, but what I got in my output file is random number of spaces instead of tab. This makes it impossible for me to process the `.ld` file with other tools like python. I do not remember having this issue before. So I am wondering whether this is a bug somewhere or has to do with the computational cluster I am using.

**Comment by chrchang** [comment]
Almost all plink 1.9 output files are space-delimited, to maximize backward compatibility with plink 1.07.

**Comment by Zepeng-Mu** [comment]
Alright, thank you so much. Although it is not one space, but 15-20 spaces. I will try plink 1.07 also.

**Comment by chrchang** [comment]
The only reason plink 1.9 uses e.g. 15-20 spaces is because plink 1.07 does the same; considerable effort was put into keeping output formatting identical whenever possible.  The point is to remove the need for plink 1.07's >100x-slower implementation.

See http://www.cog-genomics.org/plink/1.9/other#tabspace for a sed one-liner that converts plink 1.x multi-space columns to tab-delimited.
