### ISSUE TITLE
misaligned read PgfiInitPhase1 in fread branch (not mmap)

### ISSUE THREAD

**Issue by jpritikin** [chrchang/plink-ng#106]
See `PgfiInitPhase1` in `2.0/pgenlib_internal.cc`. There is `fread_unlocked(small_readbuf, 3, 1, shared_ff)` into stack allocated small_readbuf which may not be aligned. A bit later `memequal_k(fread_ptr, "l\x1b", 2)` triggers an UBSAN warning because memequal_k coerces the address to a int16 pointer.

```
(gdb) p &small_readbuf
$2 = (unsigned char (*)[3]) 0x7fffffff9845
```

**Comment by chrchang** [comment]
What platform is this?  There are quite a few cases where deliberate use of unaligned pointers is a good idea on x86.  I've tried to at least mark every function making deliberate use of unaligned pointers with #ifdef __arm__ #error "Unaligned accesses in <function name>()." #endif, to make a future ARM port practical, but that port is not going to happen until e.g. Apple produces an ARM-based laptop.

**Comment by jpritikin** [comment]
It's x86. Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

**Comment by chrchang** [comment]
The code compiles correctly on that machine, right?  I have not heard of any modern compiler which doesn't generate code with the expected behavior on x86 here.  This is undefined behavior according to the platform-independent specification for good reason, but on this platform it is not really undefined.

**Comment by jpritikin** [comment]
> The code compiles correctly on that machine, right?

I'm not a machine code expert, but if valgrind tells me I'm doing something wrong then I am inclined to listen.

**Comment by chrchang** [comment]
As mentioned above, there’s a good chance that this will be addressed in ~2021 since Apple seems to be working on a machine where it’ll matter.  I will provide a way to produce x86 builds with no unaligned accesses at that time.

But, while I care about other forms of UB on x86 (e.g. strict aliasing violations), this form is explicitly whitelisted in the plink2 codebase.  The alternatives are far worse: throw away a significant amount of performance in paranoid fear of something x86 compilers don’t actually do, or waste a lot of time writing assembly code to specify what the existing C++ code already specifies perfectly well on x86.  gcc 4.8, which I’m using for now to avoid producing binaries that afflict a bunch of users with “Kernel too old” errors, is not close to smart enough to allow a better alternative.

**Comment by jpritikin** [comment]
Your position seems crazy to me given that we're arguing about how to compare 3 bytes. That operation can't possibly be performance sensitive, but whatever. I guess I'll fix the misaligned access in my fork of your code and leave it at that.

**Comment by chrchang** [comment]
It’s not about this instance, it’s about the policy which also affects hundreds of other lines, some of which are in critical loops.  When I address this, I will address it all at once; it’s ridiculous to handle one instance at a time.
