### ISSUE TITLE
Compilation fails (for both 1.9 and 2.0)

### ISSUE THREAD

**Issue by theofilos** [chrchang/plink-ng#109]
In Ubuntu 16.04 I installed atlas and zlib with:
sudo apt-get install zlib1g
sudo apt-get install libatlas-base-dev liblapack-dev libblas-dev

and ran make in both the 1.9/ and 2.0 subdirectories. It failed because it could not file the zlib library. I was able to compile both by using " -lz" instead of looking for it at ../zlib-1.2.11/libz-32.a.

I can send a pull request if you want.

**Comment by chrchang** [comment]
This is currently controlled by whether STATIC_ZLIB or DYNAMIC_ZLIB is defined during compilation, but yes, it could be cleaned up a bit (along with 1.9 using Makefile.std instead of Makefile for obsolete reasons).  I’ll do something about this within the next two days; if it still doesn’t work out of the box for you at that point, go ahead and submit a pull request.

**Comment by chrchang** [comment]
Hmm, won't get around to this tonight, but Wednesday should be doable.  In the meantime, you mention libz-32.a; I assume this is just an unwanted artifact of the 1.9 Makefile, rather than you actually wanting a 32-bit instead of a 64-bit build?

**Comment by theofilos** [comment]
Yes libz-32a is an unwanted artifact of the Makefile. I dont want a 32-bit build instead of a 64-bit build, I just think the Makefile should link against the standard zlib library that the user decided to install, via -lz.
