### ISSUE TITLE
Load imbalance in plink2_matrix_calc.cc::CalcGrmPartThread().

### ISSUE THREAD

**Issue by LorienLV** [chrchang/plink-ng#213]
Hello.

We are experiencing load imbalance between threads in plink2_matrix_calc.cc::CalcGrmPartThread(). It seems that plink2_matrix_calc.cc::TriangleFill() assigns bigger matrices to threads with lower ids, so threads with higher ids spend most of their execution time waiting.

We are also wondering what is the reason behind using num_threads - 1 threads when the user request > 2 threads.

Thank you.

**Comment by chrchang** [comment]
TriangleFill assigns more rows to threads with earlier IDs because those matrices have fewer columns; it tries to roughly equalize matrix area.

It is generally reasonable to reserve one thread for I/O once you have enough cores.

I’m open to merging in a pull request if it exhibits better performance across all platforms, but I probably won’t spend much time trying to tune this myself in the near future; there are obvious higher priorities such as getting fully-powered merge working.

**Comment by LorienLV** [comment]
Then, there might be a problem with the number of columns. In my testcase, when executing plink2_matrix.cc::ColMajorMatrixMultiplyStridedAddassign(), these are the sizes of the two inputs matrices and the output matrix when executing with two threads:

**Thread 0**
- inmatrix1: 2504 x 144
- inmatrix2: 144 x 1771
- outmatrix: 2504 x 1771

**Thread 1**
- inmatrix1: 2504 x 144
- inmatrix2: 144 x 733
- outmatrix: 2504 x 733

Are these sizes expected? Thread 0 spends almost two times more time executing LAPACK's dgemm() function than thread 1.

**Comment by chrchang** [comment]
Hmm, yes, thread 0 forgot to actually skip the extra columns here; thanks for digging into this.  Will post a fix today.

**Comment by LorienLV** [comment]
Great! Thank you very much.

**Comment by chrchang** [comment]
Should be fixed by da8ae7b .

**Comment by LorienLV** [comment]
It is. Thank you!
