### ISSUE TITLE
skipping --glm regression - variance inflation factor for covariate 'batch=batch1' is too high

### ISSUE THREAD

**Issue by SiyangLiu** [chrchang/plink-ng#95]
Dear Chang,
We encountered the following warning when performing a logistic regression for one phenotype among 29875 cases, 29057 controls. The batch covariate is a categorical variable named "batch1, batch2, batch3, ...", referring to the batch of arrays. Therefore, each individual has a unique batch name.  I doubled check and don't think that there exists any redundant covariates. I tried to find the place emitting warning in your source code to understand what may be the problem but it seems that the warning characters don't exist in the codes in the repository. Although it is a warning not an error, no results were output.    Could you please give me some advices? Thanks.

In addition, I would like to ask when --vcf $vcf dosage=GP is used, will you consider genotype uncertainty in the glm model? Namely, given dosage=GP, are you using exact genotypes or the genotype probability in the regression model?

Look forward to your reply. Thank you very much. 
PLINK v2.00a1LM 64-bit Intel (11 Feb 2018)
Options in effect:
  --covar batch_test.xCov.txt
  --double-id
  --glm
  --id-delim @
  --out merged.format.plink
  --psam pheno.table.txt
  --threads 6
  --vcf merged.vcf.gz dosage=GP

Hostname: cngb-compute-f11-12.cngb.sz.hpc
Working directory: /home/staff
Start time: Wed Dec 12 17:50:55 2018

Random number seed: 1544608255
32062 MB RAM detected; reserving 16031 MB for main workspace.
Using up to 6 compute threads.
--vcf: 13555 variants scanned.
--vcf:
merged.format.plink-temporary.pgen
+
merged.format.plink-temporary.pvar
written.
158957 samples (58957 females, 0 males; 58957 founders) loaded from
pheno.table.txt.
13555 variants loaded from
merged.format.plink-temporary.pvar.
1 binary phenotype loaded (29875 cases, 29057 controls).
5 covariates loaded from batch_test.xCov.txt.
Warning: Skipping --glm regression on phenotype 'PHENO1' since variance
inflation factor for covariate 'batch=batch1' is too high. You may want to
remove redundant covariates and try again.

End time: Wed Dec 12 18:04:32 2018

**Comment by chrchang** [comment]
That build is almost a year old; can you try rerunning with a more recent one?

**Comment by SiyangLiu** [comment]
Dear Chang, 
When we used the latest version instead, it still emits the same error. I cannot find the corresponding sentence in the source code. 
Please find the log file below. Could you please help identify the reasons for that?

PLINK v2.00a2LM 64-bit Intel (28 Oct 2018)
Options in effect:
  --covar plink.xCov.txt
  --glm
  --out chr1_1_5000000.format.plink
  --psam chr1_1_5000000.pheno.table.txt
  --threads 6
  --vcf merged.vcf.gz dosage=DS

Hostname: cngb-compute-f10-15.cngb.sz.hpc
Working directory: step1.plink.work.sh.6416.qsub
Start time: Tue Dec 18 12:42:07 2018

Random number seed: 1545108127
32062 MiB RAM detected; reserving 16031 MiB for main workspace.
Using up to 6 compute threads.
--vcf: 16704 variants scanned.
--vcf:
chr1_1_5000000.format.plink-temporary.pgen
+
chr1_1_5000000.format.plink-temporary.pvar
written.
74997 samples (74997 females, 0 males; 74997 founders) loaded from
chr1_1_5000000.pheno.table.txt.
16704 variants loaded from
chr1_1_5000000.format.plink-temporary.pvar.
1 quantitative phenotype loaded (62717 values).
5 covariates loaded from plink.xCov.txt.
Calculating allele frequencies... done.
Warning: Skipping --glm regression on phenotype 'PHENO1' since variance
inflation factor for covariate 'batch=batch1' is too high. You may want to
remove redundant covariates and try again.

End time: Tue Dec 18 14:50:28 2018






Best,
Siyang

**Comment by chrchang** [comment]
I'd need to look at the covariates to give you an answer.

**Comment by SiyangLiu** [comment]
Dear Chang,
I have resolved this issue. It is due to erroneous labelling of the batch covariate. After fixing the labels, things go well.
I have another question. It turned out the above commands took 113.146G memory while the input vcf file is 58G. For several regions, plink2 took 250G memory. 
Does plink2 perform logistic regression for one site at a time? In this case, it should take little memory. 
Is there any suggestions for reduction of the memory?

Look forward to your reply. 
Thanks and happy New year.

**Comment by chrchang** [comment]
Use --memory to limit plink2's workspace size.

**Comment by thanhbuu04** [comment]
Hi Siyang, could you please give me what do you mean by "erroneous labelling of the batch covariate" and how did you fix it a little bit more detail?
Thank you

> Dear Chang,
> I have resolved this issue. It is due to erroneous labelling of the batch covariate. After fixing the labels, things go well.
> I have another question. It turned out the above commands took 113.146G memory while the input vcf file is 58G. For several regions, plink2 took 250G memory.
> Does plink2 perform logistic regression for one site at a time? In this case, it should take little memory.
> Is there any suggestions for reduction of the memory?
> 
> Look forward to your reply.
> Thanks and happy New year.

**Comment by chrchang** [comment]
@thanhbuu04, have you tried adding --covar-variance-standardize to your command?  If that doesn't work, can you post the .log file from your failing run?

**Comment by chrchang** [comment]
Can you rerun this with a more recent build?  That one is a year old, and there have been many bugfixes since then.

**Comment by thanhbuu04** [comment]
yes, I have rerun it, still the same error. With sample size smaller as 2700, it runs smoothly but with sample size as 10045, it returns in error as above.

**Comment by chrchang** [comment]
You probably need to find a way to make your batch/center categories less redundant before trying to perform your regression, then.

**Comment by thanhbuu04** [comment]
Thanks Chang! the problem still persist, what if I modify and treat the categorical variable as a numeric variable?
Thank you!

**Comment by thanhbuu04** [comment]
Hi Chang, I've tried to do as above, the problem still happens. Another way I have tried is to create a dummy variable with --write-covar --dummy-coding. Is it ok to do so? Thank you!

**Comment by chrchang** [comment]
That shouldn't help, since plink2 automatically does that to categorical variables.

**Comment by thanhbuu04** [comment]
Thanks Chang, I have decomposed the categorical covariate step by step with --split-cat-pheno omit-last covar-01, with "batch", that's all right. But with centre, even when I tested with only centre covariate (centerX, centerY, etc.) , the problem is the same as above but when I removed only (any) one of the centre, it ran smoothly. So basicly, I have already included that removed centre into the one that I had omited with the command above, which seems to be not fine. Because this is only a categorical covariate so when using --split-cat-pheno, I believe those decomposed covariates are not redundant but the problem still persists. I think you can have a check in Plink. Please tell me if you think of something. Hope my suggestion would help for further Plink improvement!
Thank you!

**Comment by chrchang** [comment]
If removing a single category solves the problem, that essentially proves that plink2's check is working correctly.  You need to figure out where the redundancy is in your covariates.

**Comment by thanhbuu04** [comment]
Sorry if I made you confused, please see again that I said I just used one covariate (centre), then I used the --split-cat-pheno to make 0/1 value for each of its level. Then I used these values (still only 1 covariate centre after splitting to run linear regression) to do the linear regression. Since this is a categorical covariate and split into several binary files, I only use these split covariate for the analysis, I believe it is not redundant.

Here is the original covariate file: https://www.dropbox.com/s/cyz0y34a4a473vp/covar_original.txt?dl=0
Here is the split covariate file from the original after using --split-cat-pheno: https://www.dropbox.com/s/oftufdvz7z2htkg/covariates_dummy_toy.cov?dl=0
Here is the phenotype https://www.dropbox.com/s/ow7yoel46d5tekr/phenotype.tsv?dl=0

Sorry I couldn't attach the bfiles since the size of the bed file is large (65GB)

Here is the code I used for --split-cat-pheno
```
plink2 --bfile testinp --pheno phenotype.tsv --pheno-name height --covar covar_toy.txt --split-cat-pheno omit-last covar-01 centre --write-covar --out covariates_dummy_toy
```

Here is the code I ran for linear regression:
```
plink2 --bfile testinp --pheno phenotype.tsv --pheno-name height --covar covariates_dummy_toy.cov --linear hide-covar --adjust --out testout --covar-variance-standardize
```

Here is the output:

```
Start time: Wed Feb  6 21:55:26 2019
257682 MB RAM detected; reserving 128841 MB for main workspace.
Using up to 32 threads (change this with --threads).
231068 samples (0 females, 0 males, 231068 ambiguous; 231068 founders) loaded
from ukbb_dis_random_low_rel_0.8_0.2.fam.
1133273 variants loaded from ukbb_dis_random_low_rel_0.8_0.2.bim.
1 quantitative phenotype loaded (230567 values).
21 covariates loaded from covariates_dummy_toy.cov.
--covar-variance-standardize: 21 covariates transformed.
Warning: Skipping --glm regression on phenotype 'height' since variance
inflation factor for covariate 'centre=centre10' is too high. You may want to
remove redundant covariates and try again.
End time: Wed Feb  6 21:55:27 2019
```

Here is the size of each class in the original covariate file:

```
centre1 centre10 centre11 centre12 centre13 centre14 centre15 centre16 
   16295    21112    16340    14214     8728    11036    10714    15169 
centre17 centre18 centre19  centre2 centre20 centre21 centre22  centre3 
    6360    20906     9029     8536     1171      230      340    11484 
 centre4  centre5  centre6  centre7  centre8  centre9 
   15380    14403     9560     8655     7131     4275 
```

**Comment by thanhbuu04** [comment]
Sorry if I made you confused, please see again that I said I just used one covariate (centre), then I used the --split-cat-pheno to make 0/1 value for each of its level. Then I used these values (still only 1 covariate centre after splitting to run linear regression) to do the linear regression. Since this is a categorical covariate and split into several binary files, I only use these split covariate for the analysis, I believe it is not redundant.

Here is the original covariate file: https://www.dropbox.com/s/cyz0y34a4a473vp/covar_original.txt?dl=0
Here is the split covariate file from the original after using --split-cat-pheno: https://www.dropbox.com/s/oftufdvz7z2htkg/covariates_dummy_toy.cov?dl=0
Here is the phenotype https://www.dropbox.com/s/ow7yoel46d5tekr/phenotype.tsv?dl=0

Sorry I couldn't attach the bfiles since the size of the bed file is large (65GB)

Here is the code I used for --split-cat-pheno
```
plink2 --bfile testinp --pheno phenotype.tsv --pheno-name height --covar covar_toy.txt --split-cat-pheno omit-last covar-01 centre --write-covar --out covariates_dummy_toy
```

Here is the code I ran for linear regression:
```
plink2 --bfile testinp --pheno phenotype.tsv --pheno-name height --covar covariates_dummy_toy.cov --linear hide-covar --adjust --out testout --covar-variance-standardize
```

Here is the output:

```
Start time: Wed Feb  6 21:55:26 2019
257682 MB RAM detected; reserving 128841 MB for main workspace.
Using up to 32 threads (change this with --threads).
231068 samples (0 females, 0 males, 231068 ambiguous; 231068 founders) loaded
from testinp.fam.
1133273 variants loaded from testinp.bim.
1 quantitative phenotype loaded (230567 values).
21 covariates loaded from covariates_dummy_toy.cov.
--covar-variance-standardize: 21 covariates transformed.
Warning: Skipping --glm regression on phenotype 'height' since variance
inflation factor for covariate 'centre=centre10' is too high. You may want to
remove redundant covariates and try again.
End time: Wed Feb  6 21:55:27 2019
```

Here is the size of each class in the original covariate file:

```
centre1 centre10 centre11 centre12 centre13 centre14 centre15 centre16 
   16295    21112    16340    14214     8728    11036    10714    15169 
centre17 centre18 centre19  centre2 centre20 centre21 centre22  centre3 
    6360    20906     9029     8536     1171      230      340    11484 
 centre4  centre5  centre6  centre7  centre8  centre9 
   15380    14403     9560     8655     7131     4275 
```

**Comment by chrchang** [comment]
This works if you add --vif 999, and results are identical with and without --split-cat-pheno.  Since --vif 999 is needed, the bottom line is that it's unsafe to include the centre covariate as-is.

This discussion belongs in plink2-users, not GitHub, since it isn't a plink2 bug.

**Comment by chrchang** [comment]
More precisely, interpretation of VIF is more complicated when categorical dummy variables are involved.  There are papers on this subject discussing when higher VIF might be okay.  But again, plink2 is doing its job; you're on your own if you want to try to break the usual rules.

**Comment by thanhbuu04** [comment]
Thank you very much Chang, your help is really appreciated!
